### ISSUE TITLE
TL-WN821N v6 ubuntu 18.04 kernel 4.15.0-36-generic 

### ISSUE THREAD

**Issue by mksharifinia** [Mange/rtl8192eu-linux-driver#102]
I'm beginner, 
I install driver according to readme but hotspot does not work!

my system is : 
TL-WN821N v6 ubuntu 18.04 kernel 4.15.0-36-generic 

$ nmcli device wifi hotspot ssid IRI password 123456789
 Error: Device 'wlx503eaa54e056' supports neither AP nor Ad-Hoc mode.

$ sudo lshw -C Network
  *-network                 
       description: Ethernet interface
       product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: enp3s0
       version: 0c
       serial: 38:d5:47:13:60:9c
       size: 100Mbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix vpd bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=full firmware=rtl8168g-2_0.0.1 02/06/13 ip=192.168.200.13 latency=0 link=yes multicast=yes port=MII speed=100Mbit/s
       resources: irq:25 ioport:e000(size=256) memory:f7c00000-f7c00fff memory:f0000000-f0003fff
  *-network
       description: Wireless interface
       physical id: 2
       bus info: usb@3:7
       logical name: wlx503eaa54e056
       serial: 50:3e:aa:54:e0:56
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8xxxu driverversion=4.15.0-36-generic firmware=N/A link=no multicast=yes wireless=IEEE 802.11

please help!

**Comment by daedroza** [comment]
driver=rtl8xxxu meaning you're loading the generic driver provided by the kernel.

Look at README, new instructions are added.

**Comment by mksharifinia** [comment]
Thanks .

It's ok

Best regards
