### ISSUE TITLE
Doesnt work at tp-link tl wn-822n

### ISSUE THREAD

**Issue by ghost** [Mange/rtl8192eu-linux-driver#105]
I have tp-link tl wn-822n v5 .It conects to wi-fi networks but i cant put it to a monitor mode.Help me please.

**Comment by jabil-rg02** [comment]
Please dump the contents of /etc/NetworkManager/NetworkManger.conf file

**Comment by ghost** [comment]
Thats all what I have in this file
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=false
Thank You.

**Comment by CGarces** [comment]
Please test with the last version an re-open the issue if needed.
