### ISSUE TITLE
[Thanks] Worked for me on  TP LINK model TL-WN821N V6.0

### ISSUE THREAD

**Issue by douglasjunior** [Mange/rtl8192eu-linux-driver#108]
**I just want to say: Thank you.**

This drivers solved my issues with TL-WN821N V6.0 on Ubuntu 18 and Mint 19.

**Comment by ceyzeriat** [comment]
TL-WN821N V6.0 on Ubuntu 18
Thank you - you saved my Wifi dongle's life :)

**Comment by MKRhere** [comment]
TL-WN821N V6.0 on Debian 10 Buster

I love you all. The original author, patches, @Mange for hosting it here, and the above guys who made this issue easy to find! Installation was smooth as butter, and worked seamlessly! ❤️

**Comment by douglasjunior** [comment]
My intention was even to group the keywords and help the future searches, good to know it worked.

**Comment by ceyzeriat** [comment]
Love you too!
I have a dual boot Ubuntu 18 and windows 10, and funnily, no later than today, updating window 10 broke the wifi dongle (sigh). I ended up having to remove + re-install, and it fixed it!

**Comment by vinay1904** [comment]
hi ,

I need to install in kalilinux .Please suggest

**Comment by ppavacic** [comment]
Thanks works for TL-WN821N V6.0 on Fedora 36
