### ISSUE TITLE
tryaing all the day.. thats what i have after make... same with dkms..

### ISSUE THREAD

**Issue by actlikeapro** [Mange/rtl8192eu-linux-driver#111]
that is debian vm in qubes
root@host:/home/user/rtl8192eu-linux-driver# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.67-1.pvops.qubes.x86_64/build M=/home/user/rtl8192eu-linux-driver  modules
make[1]: Entering directory '/lib/modules/4.14.67-1.pvops.qubes.x86_64/build'
make[2]: *** No rule to make target '/home/user/rtl8192eu-linux-driver/core/rtw_cmd.o', needed by '/home/user/rtl8192eu-linux-driver/8192eu.o'.  Stop.
Makefile:1523: recipe for target '_module_/home/user/rtl8192eu-linux-driver' failed
make[1]: *** [_module_/home/user/rtl8192eu-linux-driver] Error 2
make[1]: Leaving directory '/lib/modules/4.14.67-1.pvops.qubes.x86_64/build'
Makefile:1700: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by evanperryg-old** [comment]
I was able to fix this error by adding this line to the top of the makefile:

```
MAKE:=make
```
I'm still getting other errors, though. Some of them have to do with the (very weird, non-standard) configuration of the machine I'm using, but I'll post my results if I can get it to compile.

**Comment by arthurbarros** [comment]
@evanperryg was you ever able to install it from make ?
