### ISSUE TITLE
Error: Your kernel headers cannot be found

### ISSUE THREAD

**Issue by JohnDimop** [Mange/rtl8192eu-linux-driver#114]
I get this message. What does it mean?

sudo dkms install 8192cu/1.11

Your kernel headers for kernel 4.20.6-200.fc29.x86_64 cannot be found at
/lib/modules/4.20.6-200.fc29.x86_64/build or /lib/modules/4.20.6-200.fc29.x86_64/source.

**Comment by CGarces** [comment]
You must download the kernel headers
