### ISSUE TITLE
Keep throwing exception ERROR HalPwrSeqCmdParsing

### ISSUE THREAD

**Issue by yamng94** [Mange/rtl8192eu-linux-driver#122]
When i try to connect to the wifi, following error emerged for executing command "dmesg".
Moreover, my linux kernal is 4.19.0-kali4-amd64
<img width="577" alt="Capture" src="https://user-images.githubusercontent.com/32287027/55355982-52d9ad80-54fc-11e9-9b1e-c68fefd08693.PNG">
May i ask what is the root cause of the issue ? Thanks in advance

**Comment by CGarces** [comment]
I have no idea about how fix this problem
¿Can you please test this branch?
https://github.com/CGarces/rtl8192eu-linux-driver/commits/realtek-5.x.x
It contains the driver v5.6.4_35685.20191108_COEX20171113-0047 from Realtek FTP plus all the patches from 4.4.x branch.

**Comment by CGarces** [comment]
Version  v5.6.4 merged at #149 
Please test again an reopen the issue if needed
