### ISSUE TITLE
Fail at DKMS make

### ISSUE THREAD

**Issue by RAZORRZR0** [Mange/rtl8192eu-linux-driver#126]
rzr@mac:~/rtl8192eu-linux-driver$ sudo dkms install rtl8192eu/1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=5.0.0-15-generic........(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8192eu: 1.0 not found
Error! Bad return status for module build on kernel: 5.0.0-15-generic (x86_64)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.

I have Ubuntu 19.04 and i am facing this issue while installing the driver

**Comment by RAZORRZR0** [comment]
[make.log](https://github.com/Mange/rtl8192eu-linux-driver/files/3222385/make.log)
heres the make.log

**Comment by CGarces** [comment]
@RAZORRZR0 have you solved the issue? can be closed?
