### ISSUE TITLE
How to compille under Raspbian (arm7l)

### ISSUE THREAD

**Issue by omikron88** [Mange/rtl8192eu-linux-driver#128]
Hello,
How to compile under Raspbian?
It says that no rule to build modules.

$ make
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.14.98-v7+/build M=/home/pi/rtl8192eu-linux-driver  modules
make[1]: Vstupuje se do adresáře „/lib/modules/4.14.98-v7+/build“
make[1]: *** Žádné pravidlo jak vyrobit cíl „modules“. Konec.
make[1]: Opouští se adresář „/lib/modules/4.14.98-v7+/build“
Makefile:1710: návod pro cíl „modules“ selhal

**Comment by CGarces** [comment]
Please try with last version of make file and reopen the issue if needed.
