### ISSUE TITLE
Kali 4.6.0 x64 needs support!

### ISSUE THREAD

**Issue by JiangMufan** [Mange/rtl8192eu-linux-driver#13]
When I install the driver, it appears like this:
make: **\* lib/modules/4.6.0-kali1-amd64/build M=/"the driver's path" modules
Thx!

**Comment by michaelweghorn** [comment]
In general, kernel 4.6 should be supported (at least by now).

Is the problem still there for you? If so, could you possibly give some more information?

Does compiling the module fail or is the problem something else?
In case building the module fails: Can you please paste the full output here?

**Comment by michaelweghorn** [comment]
I'm closing this issue since there has been no reply in over 3 weeks. Please reopen and provide more information in case you are still having this issue.
