### ISSUE TITLE
"No rule to make target modules". Stop 

### ISSUE THREAD

**Issue by kasparov1997** [Mange/rtl8192eu-linux-driver#131]
I have TPLink -WN823N V2 and OS - ARCH LINUX 
Kernel version - 4.19.34-1-lts .
I have install dkms - 2.7.1-1 , linux-headers - 5.1.15.arch-1

My WiFi is not able to connect and led is also not blinking .
When I try to manually build the driver it says
"Entering directory '/usr/lib/modules/4.19.34-1-lts/build"
***No rule to make target 'modules'. Stop .
Leaving directory '/usr/lib/modules/4.19.34-1-lts/build
If type command "dkms install rtl8192eu/1.0"
Error ! echo
Your kernel headers for kernel 4.19.34-1-lts cannot be found at /usr/lib/modules/4.19.34-1-lts/build or /usr/lib/modules/4.19.34-1-lts/source
![IMG_20190704_011020](https://user-images.githubusercontent.com/50150424/60652496-f91fb100-9e65-11e9-9494-3a8d9a5ee13c.jpg)

**Comment by CGarces** [comment]
You must download the headers of your Kernel.

From [README.md](https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/README.md)

> 
> Install DKMS and other required tools
> 
> for normal Linux systems
> $ sudo apt-get install git linux-headers-generic build-essential dkms;

**Comment by kasparov1997** [comment]
First of all I use pacman, second thing is I have installed linux header 5.1.15 .
Is linux-header and linux-headers-generic build-esential different package??

**Comment by CGarces** [comment]
it's trying to compile over 4.19.34

Can you check your current kernel version with `uname -r`?
