### ISSUE TITLE
enabling green led on TL-WN822N v. 5

### ISSUE THREAD

**Issue by urrfaust** [Mange/rtl8192eu-linux-driver#138]
Hi,

Any chance of enabling the TX/RX led on this adapter?

thanks

**Comment by CGarces** [comment]
Sorry I don't have knowledge to do that.
If you find a patch on other rtlxxxx drivers please ping me and I'll try to port it.

**Comment by ewwhash** [comment]
who still needs it - wifi led is configuring by uncommenting this line https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/include/autoconf.h#L152
