### ISSUE TITLE
Error building module for RPI 1

### ISSUE THREAD

**Issue by Grrrolive** [Mange/rtl8192eu-linux-driver#139]
Hi, 
stuck on step 3, when it is time to choose the config platform. 
The command return is 

`bash : CONFIG_PLATFORM_I386_PC : commande introuvable`

The same message for the other command. 

I'm on a raspberry pi model 1, it is an ARM platform. 
What can I do ?

**Comment by CGarces** [comment]
Please check the readme in this repository, step 3.

**Comment by Grrrolive** [comment]
> Please check the readme in this repository, step 3.

Thank you, and sorry, I didn't understood that the "Makefile" was a file ... 
Thought it was a command ... 

I have now another problem could  you please help me ? 
This command : 

> <pre><font color="#8AE234"><b>pi@raspi</b></font>:<font color="#729FCF"><b>~/rtl8192eu-linux-driver $</b></font> sudo dkms install rtl8192eu/1.0

returns this : 

```
Error! echo
Your kernel headers for kernel 4.19.57+ cannot be found at
/lib/modules/4.19.57+/build or /lib/modules/4.19.57+/source.</pre> 
```

I tried to reboot and reinstall the kernel headers unsuccessfully... 
and look here, the kernel versions : 

```
pi@raspi:~ $ ls /usr/src/
linux-headers-4.19.66+      rtl8192eu-1.0
linux-headers-4.19.66-v7+   sense-hat
linux-headers-4.19.66-v7l+
```
```

pi@raspi:~ $ uname -r
4.19.57+
```

Thank you

**Comment by CGarces** [comment]
Looks like you don't have the kernel headers installed.
Please check that you have the packages from step one installed.

You have more detailed instructions about install kernel headers at
http://ask.xmodulo.com/install-kernel-headers-linux.html

**Comment by Grrrolive** [comment]
Yes I had an issue, impossible to get the last headers as my system wasn't upgraded. 
So I did a fresh install on my raspberry pi and and it is now working ! 
Thank you very much !
