### ISSUE TITLE
kernel headers can't be found 

### ISSUE THREAD

**Issue by Grrrolive** [Mange/rtl8192eu-linux-driver#142]
I have another problem could  you please help me ? 
This command : 

> <pre><font color="#8AE234"><b>pi@raspi</b></font>:<font color="#729FCF"><b>~/rtl8192eu-linux-driver $</b></font> sudo dkms install rtl8192eu/1.0

returns this : 

```
Error! echo
Your kernel headers for kernel 4.19.57+ cannot be found at
/lib/modules/4.19.57+/build or /lib/modules/4.19.57+/source.</pre> 
```

I tried to reboot and reinstall the kernel headers unsuccessfully... 
and look here, the kernel versions : 

```
pi@raspi:~ $ ls /usr/src/
linux-headers-4.19.66+      rtl8192eu-1.0
linux-headers-4.19.66-v7+   sense-hat
linux-headers-4.19.66-v7l+
```
```

pi@raspi:~ $ uname -r
4.19.57+
```

Thank you

_Originally posted by @Grrrolive in https://github.com/Mange/rtl8192eu-linux-driver/issues/139#issuecomment-534138144_

**Comment by CGarces** [comment]
duplicated #139
