### ISSUE TITLE
Compatibility list

### ISSUE THREAD

**Issue by dAnjou** [Mange/rtl8192eu-linux-driver#145]
Hi,

just wanted to ask whether it'd make sense to maintain a compatibility list? People could confirm working device/kernel combinations to save others some time. It took me for example a bit to find a driver that works.

Anyway, here's mine (just in case someone googles for it):

Device model | `uname -a`
------------ | -------------
TL-WN823N(EU) V3.0 | `Linux xv15 5.2.18-200.fc30.x86_64 #1 SMP Tue Oct 1 13:14:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by dAnjou** [comment]
Labeled question but closed without answer?

**Comment by CGarces** [comment]
Hi @dAnjou 
Maintain a compatibility list it's impossible. Too many adaptors and too many kernel versions.
