### ISSUE TITLE
DKMS

### ISSUE THREAD

**Issue by sistematico** [Mange/rtl8192eu-linux-driver#15]
I am running Arch Linux, and this module works perfectly. 
But how to install using dkms?
After each upgrade i need reinstall the module.

**Comment by Mange** [comment]
I have no idea.

Den mån 14 nov. 2016 13:22Lucas Saliés Brum <notifications@github.com>
skrev:

**Comment by michaelweghorn** [comment]
DKMS support has been added in the meantime, s. https://github.com/Mange/rtl8192eu-linux-driver/commit/1d714dd498c1d14415c7c33117367023b1f42a6c.

> But how to install using dkms?

The README file exlains how to install using DKMS, s. https://github.com/Mange/rtl8192eu-linux-driver#building-and-installing-using-dkms

Can this issue be closed?

**Comment by Mange** [comment]
> Can this issue be closed?

I think so.
