### ISSUE TITLE
Kernel problem on fedora 32 x86_64

### ISSUE THREAD

**Issue by proneon267** [Mange/rtl8192eu-linux-driver#186]
![Screenshot from 2020-06-21 09-30-55](https://user-images.githubusercontent.com/45512885/85216434-1d8bda80-b3a2-11ea-838f-5c235951a02e.png)
I am using a TP-LINK WN823N wifi adapter and I built and installed as follows:

    git clone https://github.com/Mange/rtl8192eu-linux-driver           ;Clone the driver repo
    cd rtl8192eu-linux-driver                                           ;Go to the cloned repo directory
    sudo dkms add .                                                     ;Add the driver to DKMS
    sudo dkms install rtl8192eu/1.0                                     ;Build and install driver
    echo "blacklist rtl8xxxu" | sudo tee /etc/modprobe.d/rtl8xxxu.conf  ;Blacklist the stock driver
    echo -e "8192eu\n\nloop" | sudo tee /etc/modules                    ;Force to activate from boot
    
    Regenerate grub config and initramfs:
        sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg    ;For UEFI systems
        sudo grub2-mkconfig -o /boot/grub2/grub.cfg             ;For BIOS systems
        dracut -v -f                                            ;Regenerate initramfs
        
    systemctl reboot -i

**Comment by yavincl** [comment]
This is normal, and happens because 8192eu is not in the kernel tree and is not signed. And it will never be because this driver's code is completely non compliant with the kernel's standards.

Just ignore the error and you will be fine.

-------- Mensagem Original --------
Ativo 21 de jun de 2020 01:22, proneon267 escreveu:
