### ISSUE TITLE
Compile rtl8192eu-linux-driver for Banana Pi R2 32 bit ARM platform

### ISSUE THREAD

**Issue by cristian-ciobanu** [Mange/rtl8192eu-linux-driver#207]
What platform should I select to compile this driver for Banana Pi R2 32 bit ARM platform ?

I guess CONFIG_PLATFORM_ARM_AARCH64 = y is only for generic ARM 64 bit.

Thank you.

**Comment by CGarces** [comment]
Hi.

You can specify the values on the comand line

try something like

`make CONFIG_PLATFORM_I386_PC=n ARCH= arm`

Also this should work.

`make CONFIG_PLATFORM_I386_PC=n CONFIG_PLATFORM_ARM_RPI=y
`
