### ISSUE TITLE
update driver based on new version from realtek 5.6.3.1

### ISSUE THREAD

**Issue by gtxaspec** [Mange/rtl8192eu-linux-driver#208]
Is there a possibility to update the driver version to the latest one?  see link, supports WPA3 and other fixes:

http://files.dlink.com.au/products/DWA-131/REV_E/Drivers/DWA-131_E1_Linux_v5.6.3.1/DWA-131_Linux_v5.6.3.1.zip

**Comment by CGarces** [comment]
Current driver is based on a newer version (v5.6.4)
See #149
https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/include/rtw_version.h
