### ISSUE TITLE
5.9.0-kali1-amd64 cannot be found

### ISSUE THREAD

**Issue by Gwinbleiddd** [Mange/rtl8192eu-linux-driver#212]
I try install it on kali linux 2020.4 and have error after "sudo dkms install rtl8192eu/1.0"
I do all stages before this.
error:

Error! echo
Your kernel headers for kernel 5.9.0-kali1-amd64 cannot be found at
/lib/modules/5.9.0-kali1-amd64/build or /lib/modules/5.9.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.

**Comment by CGarces** [comment]
Looks like you don't have linux-headers
try again with.

`sudo apt-get install build-essential libelf-dev linux-headers-$(uname -r)
`

**Comment by Gwinbleiddd** [comment]
I did it.

**Comment by Gwinbleiddd** [comment]
This don't work.
E: Unable to locate package linux-headers-5.9.0-kali1-amd64
E: Couldn't find any package by glob 'linux-headers-5.9.0-kali1-amd64'
E: Couldn't find any package by regex 'linux-headers-5.9.0-kali1-amd64'

**Comment by CGarces** [comment]
So that the problem, you don't have the headers of your kernel.
