### ISSUE TITLE
Никак не получается установить. Помогите плз.

### ISSUE THREAD

**Issue by fizsef** [Mange/rtl8192eu-linux-driver#213]
Все делаю по инструкции. Вроде все проходит без ошибок. Но команда выводит lshw -C network  driver=rtl8192eu  Несколько раз удалял все полностью и пробовал заново. Не помогло. И Адаптер странно ведет себя, то появляются сети, то исчезают...

**Comment by CGarces** [comment]
I can't help without a detailed description or logs.
