### ISSUE TITLE
Why not base it on the version 5.6.3.1?

### ISSUE THREAD

**Issue by CWZ7605** [Mange/rtl8192eu-linux-driver#217]
Dear sir,

I found the lastest official driver version is 5.6.3.1.
you can download it from this link
[http://files.dlink.com.au/products/DWA-131/REV_E/Drivers/DWA-131_E1_Linux_v5.6.3.1/DWA-131_Linux_v5.6.3.1.zip](url)

you can find all driver from this link
[http://files.dlink.com.au/products/DWA-131/REV_E/Drivers/](url)

I think the new version of the driver may be much better.
I'd like to hear your opinion.

**Comment by CGarces** [comment]
Duplicate of #208
