### ISSUE TITLE
Can't install dkms!

### ISSUE THREAD

**Issue by htb300** [Mange/rtl8192eu-linux-driver#224]
sudo dkms install rtl8192eu/1.0
                                  
Error! echo
Your kernel headers for kernel 5.9.0-kali1-amd64 cannot be found at
/lib/modules/5.9.0-kali1-amd64/build or /lib/modules/5.9.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's  #located.

I'm new to this. What should I do?

**Comment by CGarces** [comment]
Duplicate of #212
Looks like you don't have the kernel sources.
