### ISSUE TITLE
Bad return status

### ISSUE THREAD

**Issue by phpap** [Mange/rtl8192eu-linux-driver#234]
After run this on Kali linux
`sudo dkms install rtl8192eu/1.0; `

Then it said 
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=5.10.0-kali6-amd64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.0-kali6-amd64 (x86_64)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.

This is log

> DKMS make.log for rtl8192eu-1.0 for kernel 5.10.0-kali6-amd64 (x86_64)
Thu 15 Apr 2021 06:29:31 PM +07
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-kali6-amd64/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-kali6-amd64'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c: In function ‘aes_cipher’:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:1598:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
 1598 |     for (j = 0; j < 8; j++)
      |     ^~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:1601:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
 1601 |  payload_index = hdrlen + 8;
      |  ^~~~~~~~~~~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c: In function ‘aes_decipher’:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:1984:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
 1984 |     for (j = 0; j < 8; j++)
      |     ^~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_security.c:1987:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
 1987 |  payload_index = hdrlen + 8;
      |  ^~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_debug.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_debug.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_debug.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_io.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_io.c:52:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_io.c:52:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_query.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_query.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_query.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_set.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_set.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ioctl_set.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ieee80211.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ieee80211.c:25:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ieee80211.c:25:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/../hal/phydm/phydm_types.h:176,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/../hal/phydm/phydm_precomp.h:24,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/hal_data.h:25,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/../hal/phydm/phydm_types.h:176,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/../hal/phydm/phydm_precomp.h:24,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/hal_data.h:25,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c: In function ‘rtw_delba_check’:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:12427:7: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
12427 |       else
      |       ^~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:12429:8: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
12429 |        psta->recvreorder_ctrl[i].enable = _FALSE;
      |        ^~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:12430:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
12430 |       if (ret != _FAIL)
      |       ^~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:12432:8: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
12432 |        rtw_reset_continual_no_rx_packet(psta, i);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:1364:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1364 |    if(check_fwstate(pmlmepriv, WIFI_AP_STATE) == _TRUE)
      |      ^
/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_mlme_ext.c:1369:3: note: here
 1369 |   case WIFI_ASSOCREQ:
      |   ^~~~
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_wlan_util.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_wlan_util.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_wlan_util.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_vht.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_vht.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_vht.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_pwrctrl.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_pwrctrl.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_pwrctrl.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_rf.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_rf.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_rf.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_recv.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_recv.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_recv.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_sta_mgt.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_sta_mgt.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_sta_mgt.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ap.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ap.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_ap.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_xmit.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_xmit.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_xmit.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_p2p.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_p2p.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_p2p.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_tdls.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_tdls.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_tdls.c:22:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:35,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:32:
/var/lib/dkms/rtl8192eu/1.0/build/include/wifi.h:1019: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1019 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:84,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:32:
/usr/src/linux-headers-5.10.0-kali6-common/include/linux/ieee80211.h:1656: note: this is the location of the previous definition
 1656 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:82,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:32:
/var/lib/dkms/rtl8192eu/1.0/build/include/rtw_security.h:241:8: error: redefinition of ‘struct sha256_state’
  241 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-kali6-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-kali6-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-kali6-common/include/net/inet_sock.h:22,
                 from /usr/src/linux-headers-5.10.0-kali6-common/include/net/ip.h:28,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:24:
/usr/src/linux-headers-5.10.0-kali6-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-kali6-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-kali6-common/Makefile:1821: /var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-kali6-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-kali6-amd64'
make: *** [Makefile:1700: modules] Error 2

how to fix?

**Comment by CGarces** [comment]
I'm not sure about the root cause, the error at **sha256_state** confuse me.

Are you using the git code from **realtek-4.4.x**?

**sha256_state** no longer exists, was changed to **sha256_state_rtk** on #182

Please read #197 and #199

**Comment by phpap** [comment]
i didn't use it

**Comment by CGarces** [comment]
> i didn't use it

You didn't use what?

**Comment by phpap** [comment]
gitcode from realtek 4.4.x

**Comment by phpap** [comment]
ahhh yes i use from that

**Comment by CGarces** [comment]
Based on the logs provided, looks like you are using a version before #98 (2018!)
Follow the README.md and try to compile from last version (ab35c7e9672f37d75b7559758c99f6d027607687)

**Comment by josegus** [comment]
I did all the steps using branch 4.4.x in Ubuntu 21.04.. is this ok? I have a lot of errors

**Comment by CGarces** [comment]
@josegus please provide a  description of the error in a separate issue.
