### ISSUE TITLE
DKMS build fails on Fedora 36

### ISSUE THREAD

**Issue by jdb130496** [Mange/rtl8192eu-linux-driver#243]
Screenshot and log files attached. Build via DKMS fails on Fedora 36 (rawhide)
![06 Oct 2021_17 58 55_1366x768](https://user-images.githubusercontent.com/57437119/136204215-c54fd7b3-6f3f-48e4-8c5e-a161d3504c4e.png)
[make.log](https://github.com/Mange/rtl8192eu-linux-driver/files/7293779/make.log)

**Comment by CGarces** [comment]
Hi

Please appy this patch.

https://github.com/cilynx/rtl88x2bu/commit/aba46cd4dfe721df79fb24f7c9097f2b54006df3

**Comment by jdb130496** [comment]
Ok. Thank you - Will try and get back to you soon.

**Comment by jdb130496** [comment]
I installed the driver stated in your link above but same problem persists - It fails with error "Error: Connection activation failed: (53) The Wi-Fi network could not be found". I built it using make & make install and not DKMS way - driver built was successful (install -p -m 644 88x2bu.ko  /lib/modules/5.15.0-0.rc4.33.fc36.x86_64/kernel/drivers/net/wireless/) - but wifi could not be activated

**Comment by jdb130496** [comment]
Have I done something wrong? Please let me know.

**Comment by CGarces** [comment]
Hi.
You can't use 88x2bu driver from https://github.com/cilynx/rtl88x2bu/
You must use the change from that commit to modify the source code of rtl8192eu, and compile it.

**Comment by jdb130496** [comment]
Yes. I realized my mistake and copies that .c extension file to the core directory and recompiled via DKMS but bad exit still persists. make.log attached here.
[make.log](https://github.com/Mange/rtl8192eu-linux-driver/files/7294517/make.log)

**Comment by jdb130496** [comment]
Just to clarify - I copied the c source file from your given link to this driver core directory and then recompiled.

**Comment by CGarces** [comment]
> Just to clarify - I copied the c source file from your given link to this driver core directory and then recompiled.

No, you must change just the 7 lines from the commit.

**Comment by jdb130496** [comment]
I have to change 7 lines (highlighted in green colour in the source cited by you) in which c file in this source because there is no similar file like file named rtw_br_ext_c here like that in the link cited by you? Sorry for my ignorance - I am quite raw in building drivers from source in linux.

**Comment by jdb130496** [comment]
Thank you for your support but even after my many efforts to locate where to include those 7 lines in c source files,  I could not figure it out; meanwhile I found another source here https://github.com/clnhub/rtl8192eu-linux - I could build the driver from source there successfully using DKMS for Fedora rawhide  (kernel 5.15 rc4) because it already has recently included support for kernel 5.15. Best wishes.

**Comment by jdb130496** [comment]
Closing the issue for now.
