### ISSUE TITLE
Can not install Wifi Driver

### ISSUE THREAD

**Issue by TechBoym** [Mange/rtl8192eu-linux-driver#254]
![Screenshot from 2021-10-22 19-17-31](https://user-images.githubusercontent.com/88621532/138410514-b8db6e60-b49b-4a96-b37e-de23ba12bc9a.png)
┌──(prohordas㉿prohor)-[~]
└─$ cd //home/prohordas/Downloads/rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047
                                                                                
┌──(prohordas㉿prohor)-[~/Downloads/rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047]
└─$ su     
Password: 
┌──(root💀prohor)-[/home/prohordas/Downloads/rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047]
└─# make && make install
/bin/sh: 1: bc: not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-kali9-amd64/build M=/home/prohordas/Downloads/rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047  modules
make[1]: *** /lib/modules/5.10.0-kali9-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:2257: modules] Error 2

**Comment by CGarces** [comment]
rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047?
Where you get that? is a compilation from this repository?

**Comment by TechBoym** [comment]
> rtl8192EU_WiFi_linux_v5.6.3.1_34030.20190613_COEX20171113-0047? Where you get that? is a compilation from this repository?

D-Link DWA - 131 E1 Linux Driver.

**Comment by CGarces** [comment]
Looks like you not are using this repository
