### ISSUE TITLE
Updating the driver to support latest kernel

### ISSUE THREAD

**Issue by vijaytejak** [Mange/rtl8192eu-linux-driver#258]
Thanks @SatanicRaw for the support.
@vijaytejak Just follow the README.md, maybe you should use DKMS

Also you can try the rtl8xxxu module that is included in the mainline kernels, maybe support your device.

Please reopen the issue if you need more details.

_Originally posted by @CGarces in https://github.com/Mange/rtl8192eu-linux-driver/issues/256#issuecomment-967038786_

**Comment by vijaytejak** [comment]
Hi, can you pls guide, what specific to consider for updating the driver, just close and install the same steps or anything additional ?

**Comment by SatanicRaw** [comment]
Hi. If you used the command `git clone  https://github.com/Mange/rtl8192eu-linux-driver`
then just run the `git pull` command in the **rtl8192eu-linux-driver** directory, it will update the module to the latest version in the repository.
Just before building the updated module, do not forget to run the `make clean` command.

**Comment by CGarces** [comment]
Please read de Readme.md file
"Building and installing using DKMS"

**Comment by vijaytejak** [comment]
unfortunately, the directories were deleted, let me know how to update in this case.

thank you

**Comment by SatanicRaw** [comment]
`git clone https://github.com/Mange/rtl8192eu-linux-driver`

**Comment by vijaytejak** [comment]
ok,so git-clone and fresh install will do the work?

**Comment by SatanicRaw** [comment]
Yes.
