### ISSUE TITLE
Makefile:1911: modules Error 2

### ISSUE THREAD

**Issue by Electrik-rich546456** [Mange/rtl8192eu-linux-driver#276]
Hi I have a Pi 4 with ubuntu 64 on it
my uname -a is 
Linux acerpi-desktop 5.15.0-1008-raspi #8-Ubuntu SMP PREEMPT Thu May 19 11:58:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
and my uname -r is
5.15.0-1008-raspi

I receive this error 
make all
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/5.15.0-1008-raspi/build M=/home/acer-pi/rtl8188eus  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-1008-raspi'
Makefile:705: arch/aarch64/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/aarch64/Makefile'. Stop.
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-1008-raspi'
make: *** [Makefile:1911: modules] Error 2

how do i get the files i need ?

**Comment by r-value** [comment]
Hello, I changed `dkms.conf` this way and get it worked:

```diff
 AUTOINSTALL="yes"
-MAKE="'make' all KVER=${kernelver}"
+MAKE="'make' all ARCH=arm64 KVER=${kernelver}"
 CLEAN="make clean"
```
