### ISSUE TITLE
pi 1b Volumio-3.301 modprobe error

### ISSUE THREAD

**Issue by gameboycool** [Mange/rtl8192eu-linux-driver#277]
for build process, I got error
/lib/modules/5.10.92+/build not found
so I create symbol link to make file
ln -s /lib/modules/5.10.103+/build /lib/modules/$(uname -r)/build

I could make and make install
then modprobe show error

volumio@volumio:/mnt/INTERNAL/rtl8192eu-linux-driver$ sudo make install
install -p -m 644 8192eu.ko  /lib/modules/5.10.92+/kernel/drivers/net/wireless/
/sbin/depmod -a 5.10.92+
volumio@volumio:/mnt/INTERNAL/rtl8192eu-linux-driver$ sudo modprobe 8192eu
modprobe: ERROR: could not insert '8192eu': Exec format error

******for debug******
volumio@volumio:/mnt/INTERNAL/rtl8192eu-linux-driver$ sudo insmod 8192eu.ko
insmod: ERROR: could not insert module 8192eu.ko: Invalid module format

volumio@volumio:/mnt/INTERNAL/rtl8192eu-linux-driver$ dmesg | tail
[   78.537543] SMSC LAN8700 usb-001:003:01: attached PHY driver [SMSC LAN8700] (mii_bus:phy_addr=usb-001:003:01, irq=POLL)
[   78.559655] smsc95xx 1-1.1:1.0 eth0: Link is Down
[   78.564932] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   80.653564] smsc95xx 1-1.1:1.0 eth0: Link is Up - 100Mbps/Full - flow control off
[ 1161.214632] 8192eu: disagrees about version of symbol module_layout
[ 1658.117742] 8192eu: disagrees about version of symbol module_layout
[10496.194456] 8192eu: disagrees about version of symbol module_layout
[10529.428213] 8192eu: disagrees about version of symbol module_layout
[10583.219681] 8192eu: disagrees about version of symbol module_layout
[11057.455768] 8192eu: disagrees about version of symbol module_layout

**Comment by CGarces** [comment]
Looks like you have compiled the module against a different version of the kernel than is running
5.10.103 vs 5.10.92
Please reopen the issue is not is your case
