### ISSUE TITLE
Driver installation stalls on Raspberry pi B plus. 

### ISSUE THREAD

**Issue by vasudeva78** [Mange/rtl8192eu-linux-driver#279]
Hi @CGarces ,

I use **32 bit Raspberry Pi Model B Plus** running on  5.10.103+ Linux Kernel. When I clone branch **realtek-4.4.x**, amend the Makefile
and install the driver using **sudo dkms install rtl8192eu/1.0**, the terminal just shows series of dots.

Please see error snapshot as attached.

![driver-error](https://user-images.githubusercontent.com/26213375/179728444-a215ac8c-e790-4aac-a4cf-1c05bfe65975.jpg)
 
Can I get some help please? Many thanks.

**Comment by Ectalite** [comment]
Just wait for it to finish. It takes easily 10 minutes on my raspberry pi 4
