### ISSUE TITLE
Building error on Kali 5.18.0-kali5-amd64

### ISSUE THREAD

**Issue by AlanFletes** [Mange/rtl8192eu-linux-driver#281]
I tried to install the driver following the instructions but got stuck in the sudo dkms install rtl8192eu/1.0 command, there are several errors in the make process.

I'll attach the log file

[make.log](https://github.com/Mange/rtl8192eu-linux-driver/files/9276397/make.log)
.

**Comment by CGarces** [comment]
have you installed the kernel headers?
