### ISSUE TITLE
Installation error on raspberry pi 2 + octopi

### ISSUE THREAD

**Issue by renatopestana** [Mange/rtl8192eu-linux-driver#287]
I am trying to install the driver on a raspberry pi 2 running the Linux octopi 5.15.61-v7+.

After executing the recommended steps I am getting the following error:

```
$ sudo dkms install rtl8192eu/1.0

"Error! echo
You kernel headers for kernel 5.15.61-v7+ cannot be found at /lib/modules/5.15.61-v7+/build or /lib/modules/5.15.61-v7+/source."
```

All available updates have been done with success:
```
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt dist-update -y
$ sudo rpi-update
```

I am using the Intelbras IWA 3000 (RTL8192EU) wi-fi<=>usb and I got success by installing it on a raspberry pi zero using Linux raspberry 5.15.61+.

**Comment by CGarces** [comment]
just double check that you have the kernel headers as the error said.
