### ISSUE TITLE
Can't build module under Linux kernel 4.10.13

### ISSUE THREAD

**Issue by BillKalaitzis** [Mange/rtl8192eu-linux-driver#32]
After installing the latest linux kernel as of time (4.10.13) dkms is unable to build the module.
Here is the make log of dkms:

>  DKMS make.log for rtl8192eu-4.4 for kernel 4.10.13 (x86_64)
Sun Apr 30 15:43:15 EEST 2017
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.10.13/build M=/var/lib/dkms/rtl8192eu/4.4/build  modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.13'
  CC [M]  /var/lib/dkms/rtl8192eu/4.4/build/core/rtw_cmd.o
In file included from ./include/linux/srcu.h:33:0,
                 from ./include/linux/notifier.h:15,
                 from ./include/linux/memory_hotplug.h:6,
                 from ./include/linux/mmzone.h:751,
                 from ./include/linux/gfp.h:5,
                 from ./include/linux/slab.h:14,
                 from /var/lib/dkms/rtl8192eu/4.4/build/include/osdep_service_linux.h:29,
                 from /var/lib/dkms/rtl8192eu/4.4/build/include/osdep_service.h:41,
                 from /var/lib/dkms/rtl8192eu/4.4/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/4.4/build/core/rtw_cmd.c:22:
./include/linux/netfilter.h: In function ‘nf_hook’:
./include/linux/netfilter.h:205:33: error: dereferencing pointer to incomplete type ‘struct net’
  hook_head = rcu_dereference(net->nf.hooks[pf][hook]);
                                 ^
./include/linux/rcupdate.h:610:10: note: in definition of macro ‘__rcu_dereference_check’
  typeof(*p) *________p1 = (typeof(*p) *__force)lockless_dereference(p); \
          ^
./include/linux/rcupdate.h:790:28: note: in expansion of macro ‘rcu_dereference_check’
 #define rcu_dereference(p) rcu_dereference_check(p, 0)
                            ^~~~~~~~~~~~~~~~~~~~~
./include/linux/netfilter.h:205:14: note: in expansion of macro ‘rcu_dereference’
  hook_head = rcu_dereference(net->nf.hooks[pf][hook]);
              ^~~~~~~~~~~~~~~
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/rtl8192eu/4.4/build/core/rtw_cmd.o' failed
make[2]: *** [/var/lib/dkms/rtl8192eu/4.4/build/core/rtw_cmd.o] Error 1
Makefile:1490: recipe for target '_module_/var/lib/dkms/rtl8192eu/4.4/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8192eu/4.4/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.13'
Makefile:1685: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by nomadmzl** [comment]
Try this: https://github.com/CGarces/rtl8192eu-linux-driver/tree/v4.4.1  or this: https://github.com/masterzorag/RTL8192EU-linux/tree/linux-4.11

Kernels 4.7 up to 4.11 supported.
