### ISSUE TITLE
Driver isn't compiling

### ISSUE THREAD

**Issue by Blu3cr0ss** [Mange/rtl8192eu-linux-driver#325]
I updated my arch after not updating it for 2 weeks. No internet even with Android USB tethering. 
![IMG_20231003_220755.jpg](https://github.com/Mange/rtl8192eu-linux-driver/assets/49835293/6f462b9e-fc79-410b-bcc0-05e77983d9aa)

**Comment by CGarces** [comment]
I need a proper log to see the compilation error.
