### ISSUE TITLE
Driver failed to install on kernel 6.7 (Manjaro)

### ISSUE THREAD

**Issue by Jose-Rondon** [Mange/rtl8192eu-linux-driver#332]
<p>Terminal results:</p>

<details>
<pre><code>Deprecated feature: REMAKE_INITRD (/var/lib/dkms/rtl8192eu/1.0/source/dkms.conf)
Error! Bad return status for module build on kernel: 6.7.0-0-MANJARO (x86_64)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod rtl8192eu/1.0 -k 6.7.0-0-MANJARO' exited 10
==> dkms install --no-depmod 8192eu/r293.f2fc8af -k 6.7.0-0-MANJARO
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/8192eu/r293.f2fc8af/source/dkms.conf)
Error! Bad return status for module build on kernel: 6.7.0-0-MANJARO (x86_64)
</pre></code>
</details>

<p>make.log content:</p>

<details>
<pre><code>DKMS make.log for 8192eu-r293.f2fc8af for kernel 6.7.0-0-MANJARO (x86_64)
mar 16 ene 2024 20:19:33 -04
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.7.0-0-MANJARO/build M=/var/lib/dkms/8192eu/r293.f2fc8af/build  modules
make[1]: se entra en el directorio '/usr/lib/modules/6.7.0-0-MANJARO/build'
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme.o
En el fichero incluido desde ./include/linux/string.h:295,
                 desde ./include/linux/bitmap.h:12,
                 desde ./include/linux/cpumask.h:12,
                 desde ./arch/x86/include/asm/paravirt.h:17,
                 desde ./arch/x86/include/asm/cpuid.h:62,
                 desde ./arch/x86/include/asm/processor.h:19,
                 desde ./arch/x86/include/asm/timex.h:5,
                 desde ./include/linux/timex.h:67,
                 desde ./include/linux/time32.h:13,
                 desde ./include/linux/time.h:60,
                 desde ./include/linux/stat.h:19,
                 desde ./include/linux/module.h:13,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/basic_types.h:37,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/drv_types.h:26,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/../hal/phydm/phydm_types.h:215,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/../hal/phydm/phydm_precomp.h:29,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/hal_data.h:20,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme.c:17:
En la función ‘fortify_memcpy_chk’,
    incluido en línea de ‘rtw_restructure_ht_ie’ en /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme.c:4744:2:
./include/linux/fortify-string.h:579:25: aviso: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Wattribute-warning]
  579 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme_ext.o
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme_ext.c: En la función ‘rtw_txpwr_init_regd’:
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme_ext.c:197:21: aviso: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  197 |                 if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_NONE)) == 0)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
En el fichero incluido desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/drv_types.h:41,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme_ext.c:17:
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/rtw_rf.h:176:14: nota: source object ‘regd_name’ of size 0
  176 |         char regd_name[0];
      |              ^~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mlme_ext.c:199:26: aviso: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  199 |                 else if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_WW)) == 0)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/rtw_rf.h:176:14: nota: source object ‘regd_name’ of size 0
  176 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.o
En el fichero incluido desde /var/lib/dkms/8192eu/r293.f2fc8af/build/include/drv_types.h:39,
                 desde /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:17:
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c: En la función ‘dump_txpwr_lmt’:
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:899:67: aviso: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  899 |                                                                 , strcmp(ent->regd_name, rfctl->regd_name) == 0 ? rf_path_char(path) : ' ');
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/rtw_debug.h:202:46: nota: en definición de macro ‘_RTW_PRINT_SEL’
  202 |                         _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                                              ^~~
En el fichero incluido desde /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:18:
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/hal_data.h:335:14: nota: source object ‘regd_name’ of size 0
  335 |         char regd_name[0];
      |              ^~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c: En la función ‘_rtw_txpwr_lmt_get_by_name’:
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:1141:21: aviso: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1141 |                 if (strcmp(ent->regd_name, regd_name) == 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/hal_data.h:335:14: nota: source object ‘regd_name’ of size 0
  335 |         char regd_name[0];
      |              ^~~~~~~~~
En la función ‘_rtw_txpwr_lmt_get_by_name’,
    incluido en línea de ‘rtw_txpwr_lmt_get_by_name’ en /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:1158:8:
/var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rf.c:1141:21: aviso: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1141 |                 if (strcmp(ent->regd_name, regd_name) == 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/hal_data.h: En la función ‘rtw_txpwr_lmt_get_by_name’:
/var/lib/dkms/8192eu/r293.f2fc8af/build/include/hal_data.h:335:14: nota: source object ‘regd_name’ of size 0
  335 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.o
/var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.c: En la función ‘cfg80211_rtw_connect’:
/var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.c:3899:32: aviso: implicit conversion from ‘enum mlme_auth_type’ to ‘enum nl80211_auth_type’ [-Wenum-conversion]
 3899 |                 sme->auth_type = MLME_AUTHTYPE_SAE;
      |                                ^
/var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.c: En el nivel principal:
/var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.c:9896:26: error: inicialización de ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ desde un tipo de puntero ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ incompatible [-Werror=incompatible-pointer-types]
 9896 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.c:9896:26: nota: (cerca de la inicialización de ‘rtw_cfg80211_ops.change_beacon’)
cc1: algunos avisos se tratan como errores
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/8192eu/r293.f2fc8af/build/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** [/usr/lib/modules/6.7.0-0-MANJARO/build/Makefile:1911: /var/lib/dkms/8192eu/r293.f2fc8af/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: se sale del directorio '/usr/lib/modules/6.7.0-0-MANJARO/build'
make: *** [Makefile:2287: modules] Error 2
</pre></code>
</details>

**Comment by CGarces** [comment]
Fixed by #331

**Comment by Jose-Rondon** [comment]
Great!, thank you
