### ISSUE TITLE
kernel 4.4.50-v7+ cannot be found

### ISSUE THREAD

**Issue by loskiq** [Mange/rtl8192eu-linux-driver#38]
`root@raspberrypi:~/rtl8192eu-arm-linux-driver-master# dkms install rtl8192eu/1.0`
`Error! echo`
`Your kernel headers for kernel 4.4.50-v7+ cannot be found at`
`/lib/modules/4.4.50-v7+/build or /lib/modules/4.4.50-v7+/source.`

What is this?

**Comment by gilcu3** [comment]
do you have your kernel headers installed? You need to do something like this:
`sudo apt-get install raspberrypi-kernel-headers`

**Comment by PanderMusubi** [comment]
https://github.com/Mange/rtl8192eu-linux-driver/pull/50

**Comment by CGarces** [comment]
Closed by #50
