### ISSUE TITLE
add blacklist and disable-power-manager files

### ISSUE THREAD

**Issue by F1ash** [Mange/rtl8192eu-linux-driver#39]
It need for building the akmods.
Same here:  https://github.com/pvaret/rtl8192cu-fixes

I tryed to build akmod package and did rewrite necessary files:
https://github.com/F1ash/rtl8192eu-kmod-common/blob/master/blacklist-native-rtl8192.conf
https://github.com/F1ash/rtl8192eu-kmod-common/blob/master/8192eu-disable-power-management.conf

The installed kernel module works, but i can't use adapter as AP. And in dmesg periodically filled by module messages.

TP-LINK TL-WN823N

`$ uname -r : 
4.12.0-0.rc3.git3.2.fc27.x86_64`

**Comment by CGarces** [comment]
I'm not sure it a newer version will fix you problems
https://github.com/CGarces/rtl8192eu-linux-driver/tree/v4.4.1
See #36 for reference
