### ISSUE TITLE
D-Link DWA-131 rev E1 is not supported in default branch (realtek-4.4.x)

### ISSUE THREAD

**Issue by serg-z** [Mange/rtl8192eu-linux-driver#41]
> Drivers for the rtl8192eu chipset for wireless adapters **(D-Link DWA-131 rev E1 included!)**

Turns out USB_DEVICE(0x2001, 0x3319) was removed in 9dde4572b40e248bb41b56d67857bcb01552eeea

**Comment by Mange** [comment]
If someone could either backport whatever added support for it that would
be excellent. Otherwise we'll have to rewrite the README to point to master
for that device instead.

Den mån 10 juli 2017 08:25Sergey Zhuravlevich <notifications@github.com>
skrev:

**Comment by CGarces** [comment]
Hi @serg-z 
I have created a PR to fix this problem.
Can you compile the driver from [there](https://github.com/CGarces/rtl8192eu-linux-driver/tree/fix_dlink_id) or [apply this patch](https://github.com/Mange/rtl8192eu-linux-driver/commit/d1b2b64e6e514601180cd032db2018445dbd8369.patch)?
Just to confirm that only the USB id is needed and the device works properly on this new branch

**Comment by navene** [comment]
Patch provided by @CGarces worked for me. I used it for installing 8192eu driver for D-link DWA131 in linux mint 18.2 (Kernel version - 4.8.0-53-generic)

**Comment by CGarces** [comment]
Thanks @rnavene for your feedback, patch merged.

**Comment by ADITYASHAH2310** [comment]
@navene and @CGarces  sir i have D-Link DWA-131 Wireless N Nano USB Adapter(rev.E) RTL8192eu and i want to use it in virtual box under linux environment.i am able to all stuffs like monitor mode ,airomon-ng and deauthentiaation but when i need to connect to wifi under linux environment (not using NAT network),then its not connecting to network.i have not downloaded any driver for it.can you guide me the steps for correcting it. As i am electrical student ,i am new to linux and its terminal command ,so if you can guide me for the commadns then it will be a great hel to me
