### ISSUE TITLE
Can't connect to any networks

### ISSUE THREAD

**Issue by karl6994** [Mange/rtl8192eu-linux-driver#48]
Hello everyone, I can't make the wifi dongle connect to either my extender or my router.. 
I got the driver installed right, it displays the networks & appropriately shows the ranges, but it keeps prompting me for the network password & won't connect.. I have tried the solutions on the other post, the /etc/modules thing, and that doesn't seem to work either :/ 
I've tried rebooting, I've tried modprobe -r and modprobing, I've tried installing it normally & via DKMS.. not sure why it won't connect...

**Comment by IIETP** [comment]
I had this issue too. And I've tried modprobe, blacklist, etc. But when i tried to connect with wpa_supplicant in terminal, it has connected without any problem.
In my Debian 9 wicd solved this problem:
`sudo apt install wicd`

**Comment by CGarces** [comment]
Thanks @IIETP 
You have any link to the NetworkManager bug?

**Comment by IIETP** [comment]
Here it is: https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1681513

**Comment by shvchk** [comment]
Relevant Network Manager bug: https://bugzilla.gnome.org/show_bug.cgi?id=777523

**Comment by karl6994** [comment]
If not for the github notifications, I would've never been able to find this... Odd I can't find it in the list of issues... Just trying the fix now, and it worked!!!! Hurray!!! Thank you!!
