### ISSUE TITLE
Works on my Ubuntu (studio) 16.04.3 but only after plug out and in

### ISSUE THREAD

**Issue by dirk-vanda** [Mange/rtl8192eu-linux-driver#60]
I installed this driver on my Ubuntu (studio) 16.04.3 and rebooted. When I plugged in the wifi dongle, it works. But when I reboot with the dongle plugged in, it doesn't work (it doesn't detect any wifi signals) until I remove it and plug it back in. Then it recognizes wifi signals and connects to mine.
Can anyone help? How can the dongle work without plugging it out and in?

**Comment by akana** [comment]
u should try

`sudo -i`
`echo 8192eu >> /etc/modules`
`exit`

**Comment by dirk-vanda** [comment]
Thanks a lot for this suggestion @akana . I works perfect now. I rebooted several times and the 8192eu module now automatically detects the Wifi signals. It isn't necessary to plug the dongle in and out any more.
I really appreciate your help.
Dirk

**Comment by akana** [comment]
@dirk-vanda you're welcome ;)
