### ISSUE TITLE
Module rtl8192eu not loaded

### ISSUE THREAD

**Issue by ghost** [Mange/rtl8192eu-linux-driver#68]
modprobe: WARNING: Module rtl8192eu not found in directory /lib/modules/4.9.59+
:((

**Comment by gilcu3** [comment]
last time I used it the module name was 8192eu.
`# modprobe 8192eu`
should work :)

**Comment by PanderMusubi** [comment]
@ghost, is this till an issue? Otherwise, please close this report.

**Comment by CGarces** [comment]
Close due lack of feedback
