### ISSUE TITLE
TL-WN822N V 4.0 can connect to open networks but not WPA2-PSK

### ISSUE THREAD

**Issue by guysoft** [Mange/rtl8192eu-linux-driver#72]
Hey all,
So got the driver and compiled it, however I can connect only to open wifi networks, any attempt to connect to a WPA2 authenticated network fails.

I have a few other wifi devices and they seem to connect to the network fine.

Using Ubuntu 17.04, kernel 4.10.0-28-generic.

**Comment by MikTur** [comment]
Hi, do you managed in someway to fix this issue? I just opened one claiming the same. Thanks.

**Comment by CGarces** [comment]
Duplicate of #64 
See fix of `/etc/NetworkManager/conf.d/30-mac-randomization.conf` inside the comments.
