### ISSUE TITLE
Ubuntu 16.04 kernel 4.13.0-32

### ISSUE THREAD

**Issue by sealyau** [Mange/rtl8192eu-linux-driver#77]
Hi Guys,
not sure what info is required but when following the normal install process i was having issues with 70% packet loss on what should of been a stable connection, 
after changing the make file to turn off power management, and set tx power to max the issue seems to have been resolved.

**Comment by PanderMusubi** [comment]
do you have the same issues in Ubuntu 18.04?

**Comment by CGarces** [comment]
Please try with last version of make file and reopen the issue if needed.
