### ISSUE TITLE
install: cannot stat ‘8192eu.ko’: No such file or directory

### ISSUE THREAD

**Issue by farazappy** [Mange/rtl8192eu-linux-driver#8]
Using `make install` gives me the following : 
`install -p -m 644 8192eu.ko  /lib/modules/4.3.0-kali1-amd64/kernel/drivers/net/wireless/
install: cannot stat ‘8192eu.ko’: No such file or directory
Makefile:1341: recipe for target 'install' failed
make: *** [install] Error 1`

Help is appreciated!

**Comment by Mange** [comment]
Did you run "make" first?

Den mån 1 aug. 2016 09:39farazappy <notifications@github.com> skrev:

**Comment by farazappy** [comment]
Well I solved that issue but now airmon-ng returns a tabular data and under `Driver` it says `?????`

Any fix?

**Comment by Mange** [comment]
No. Let me know if you find anything. 😯

Den tis 9 aug. 2016 19:21farazappy <notifications@github.com> skrev:

**Comment by nomadmzl** [comment]
Maybe [comment #11 could be related](https://github.com/CGarces/rtl8192eu-linux-driver/issues/1).

**Comment by daliboss** [comment]
How did you fix it

**Comment by Aspect9** [comment]
the Linux Drivers for the Wn722n V3 beta version are not working! cannot "make" or "make install" it presents "Error-1" cannot locate - Does anyone have any ideas? tryna get the V3 working on linux - Kali failed miserably... -_-

**Comment by CGarces** [comment]
Version  v5.6.4 merged at #149 
Please test again an reopen the issue if needed
