### ISSUE TITLE
Stuck since 3 days #i'm noob

### ISSUE THREAD

**Issue by dinsomnolence** [Mange/rtl8192eu-linux-driver#85]
root@kali2018:~/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417# make install
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
install -p -m 644 8188eu.ko  /lib/modules/4.15.0-kali2-amd64/kernel/drivers/net/wireless/
install: cannot stat '8188eu.ko': No such file or directory
Makefile:1374: recipe for target 'install' failed
make: *** [install] Error 1

Just started learning 
Day 3 of installation and still stuck can't resolve this and start "Monitor mode on"
Help is appreciated !

**Comment by foursixnine** [comment]
@dinsomnolence did you run make modules before? :) Probably you fixed this already?

Usually you want to `make all` and then `make install`
