### ISSUE TITLE
Kernel 4.16 - driver do not work with secured APNs (when secure key is required) - led status is not working as well

### ISSUE THREAD

**Issue by MikTur** [Mange/rtl8192eu-linux-driver#86]
Hi all :)
Just as title says when the driver is being compiled against kernel 4.16 headers it then stops working with secured APNs, the green led status also stops to work.
Does anyone has a cure for that? :)
Thanks

**Comment by MikTur** [comment]
P.S. It seems that the handshaking procedure is taking too much as the connection may sometime fail for an open APN also.

**Comment by CGarces** [comment]
Hi
Change /etc/NetworkManager/conf.d/30-mac-randomization.conf as described on #64 works for you?

**Comment by MikTur** [comment]
Hola Carlos :) the trick did it :) Thank you so much!
P.S. Just as a minor...do you know why the led status is not working anymore?

**Comment by CGarces** [comment]
No idea about the led indicator
