### ISSUE TITLE
Less verbose output

### ISSUE THREAD

**Issue by morfikov** [Mange/rtl8192eu-linux-driver#9]
Is there a way to set some verbosity level so the log wasn't that messy?

**Comment by Mange** [comment]
I don't know.

Den fre 12 aug. 2016 19:11Mikhail Morfikov <notifications@github.com> skrev:

**Comment by Silvia-** [comment]
Commenting out line 374 of include/autoconf.h did the trick for me, i.e. change:
`#define CONFIG_DEBUG /* DBG_871X, etc... */
`
to:
`//#define CONFIG_DEBUG /* DBG_871X, etc... */
`

HTH

**Comment by jonseymour** [comment]
PR #27 implements @Silvia-'s suggestion. Thank you, @Silvia-.

**Comment by CGarces** [comment]
Fixed by https://github.com/Mange/rtl8192eu-linux-driver/commit/0af336b999ff9b29477a205117410f9947a58fdd
