### ISSUE TITLE
Ubuntu 18.04 4.15.0-23-generic slow down

### ISSUE THREAD

**Issue by rom1504** [Mange/rtl8192eu-linux-driver#90]
Hi,
I upgraded to the last ubuntu (18.04) and the adapter got really slow (80Mb/s before to 10Mb/s after)
Do you know if there's something to upgrade about this here ?

**Comment by daedroza** [comment]
I can confirm.
Is there a way around this?
I can provide logs or something to help around here. (TP-Link WN822N)

**Comment by daedroza** [comment]
I was able to solve this problem by blacklisting the rtl8xx2 module & forcing 8192eu module to start at boot.
Really thanks & grateful for this driver @CGarces

**Comment by rom1504** [comment]
@daedroza could you provide instructions on how to do that ? it would really help !

**Comment by daedroza** [comment]
### Install RTL8192EU Driver
`git clone https://github.com/Mange/rtl8192eu-linux-driver;`
`cd rtl8192eu-linux-driver;`
`sudo dkms add .;`
`sudo dkms install rtl8192eu/1.0;`

### Blacklist RTL8XXXU Driver
`echo "blacklist rtl8xxxu" | sudo tee /etc/modprobe.d/rtl8xxxu.conf;`

### Resolve Idle PM issues (Check issue #94)
`echo "options 8192eu rtw_power_mgnt=0 rtw_enusbss=0" | sudo tee /etc/modprobe.d/8192eu.conf;`

### Force RTL8192EU Driver to be active at boot
`echo -e "8192eu\n\nloop" | sudo tee /etc/modules;`

### Update changes
`sudo update-grub; sudo update-initramfs -u;`

### Reboot
`systemctl reboot -i;`

I was initially frustrated that WN822N Router was shitty on my Linux Mint. I ended up fixing TP-Link provided driver until I found this Mange's RTL8912EU driver which has full support for Linux/Windows compilation. After installing this driver, I'm kind of happy with the performance.

I hope this resolves your problem.

**Comment by CGarces** [comment]
Thanks @daedroza, fell free to send a PR updating the readme with your instructions

**Comment by rom1504** [comment]
@daedroza I followed your instructions and indeed it's now back to normal speeds. Thank you!
