### ISSUE TITLE
build the driver for openwrt17.01.0 with error

### ISSUE THREAD

**Issue by VanillaJelly** [Mange/rtl8192eu-linux-driver#91]
i build the driver for openwrt 17.01.0 (linux 4.4.92), it appear the error (8192.ko is missing)
command: make -C "/opt/openwrt/source-17.01.4/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/linux-brcm2708_bcm2710/linux-4.4.92" ARCH="arm" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-"  modules

**Comment by CGarces** [comment]
Please provide a full log of the error and reopen de issue if needed
