### ISSUE TITLE
Device Need to unplug and replug to USB for connection to work on Ubuntu 18.04

### ISSUE THREAD

**Issue by devNaresh** [Mange/rtl8192eu-linux-driver#94]
I am using TP-link TL823N V2 which is based on rtl8192eu wiresless adapter. Everytime I start the computer, the wifi is stopped from connecting with the message Connection Failed (Activation of network connection failed), even though it shows available networks. It connects after I unplug and replug the wifi adapter. The only problem I have that each time I start the pc, I have to unplug and replug my adapter from the back of the CPU Cabinet. Even i am getting very low signal strength on ubuntu but in widows signal is strong. Any idea why its happening?

**Comment by devNaresh** [comment]
Below command solved the issue for me.

`echo "options 8192eu rtw_power_mgnt=0 rtw_enusbss=0" | sudo tee /etc/modprobe.d/8192eu.conf
echo "blacklist rtl8xxxu" | sudo tee /etc/modprobe.d/rtl8xxxu.conf`

**Comment by pdimh** [comment]
Thanks for the tip, i have the same device and had the same problem.

**Comment by CGarces** [comment]
Issue solved by https://github.com/Mange/rtl8192eu-linux-driver/issues/94#issuecomment-407698097
