### ISSUE TITLE
Modprobe dont load module(slackware64 current)

### ISSUE THREAD

**Issue by M3rsy** [Mange/rtl8192eu-linux-driver#96]
Hello guys and thanks  , a try to install the driver  ando is good with dkms, i have linuex header , building essential  , i have the 8192eu.io on lib/modules/4.14.56/ 
When i try to.load with modprobe this is rhe output. 

[   13.851273] usb 2-1.4: RTL8192EU rev B (SMIC) 2T2R, TX queues 3, WiFi=1, BT=0, GPS=0, HI PA=0
[   13.851682] usb 2-1.4: RTL8192EU MAC: 50:3e:aa:3f:a1:f4
[   13.852100] usb 2-1.4: rtl8xxxu: Loading firmware rtlwifi/rtl8192eu_nic.bin
[   13.873820] usb 2-1.4: Firmware revision 19.0 (signature 0x92e1)
[   13.879159] do the RAM reset
[   14.829281] usb 2-1.4: rtl8192eu_rx_iqk_path_a: Path A RX IQK failed!
[   14.862030] usb 2-1.4: rtl8192eu_rx_iqk_path_a: Path A RX IQK failed!
[   14.902029] usb 2-1.4: rtl8192eu_rx_iqk_path_b: Path B RX IQK failed!
[   14.934778] usb 2-1.4: rtl8192eu_rx_iqk_path_b: Path B RX IQK failed!
[   15.028902] usb 2-1.4: rtl8192eu_rx_iqk_path_b: Path B RX IQK failed!
[   15.073866] usbcore: registered new interface driver rtl8xxxu
[   15.270500] fuse init (API version 7.26)
[   15.782472] EXT4-fs (sda1): re-mounted. Opts: (null)
[   27.749418] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
[   27.820430] EXT4-fs (sda4): mounted filesystem with ordered data mode. Opts: (null)
[   30.092715] 8192eu: loading out-of-tree module taints kernel.
[   30.094334] 8192eu: Unknown symbol __vfs_read (err 0)
[   31.224496] r8169 0000:02:00.0 eth0: link down
[   31.224502] r8169 0000:02:00.0 eth0: link down
[   31.393839] 8021q: 802.1Q VLAN Support v1.8
[   32.856722] r8169 0000:02:00.0 eth0: link up
[   33.653148] NET: Registered protocol family 10
[   33.658516] Segment Routing with IPv6
[   42.293146] NET: Registered protocol family 4
[   42.296876] NET: Registered protocol family 3
[   42.298952] NET: Registered protocol family 5
[   43.184318] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 7362.834541] 8192eu: Unknown symbol __vfs_read (err 0)
[ 7818.072548] 8192eu: Unknown symbol __vfs_read (err 0)
[ 7877.023588] 8192eu: Unknown symbol __vfs_read (err 0)
[ 8157.424290] 8192eu: Unknown symbol __vfs_read (err 0)

**Comment by CGarces** [comment]
Looks like you have compiled the module for a different kernel version.
